### ISSUE TITLE
Don't symlink ~/.gitconfig to the dotfile gitconfig

### ISSUE THREAD

**Issue by ARamsey118** [Serubin/dotfiles#14]
If the symlink is created, the file could accidentally be added to the repo. Copying .gitconfig to the home directory and using ~/.dotfiles.info to add user and email in after an update is better (though users should have a warning that their current git config is being overwritten)

**Comment by Serubin** [comment]
Closed with 012dfdccd72cf024714c7b17c4c7c4076b70c767
