### ISSUE TITLE
Make molokia a vim plugin 

### ISSUE THREAD

**Issue by ARamsey118** [Serubin/dotfiles#17]
I think Vundle can manage molokia as well

**Comment by Serubin** [comment]
Removed in favor of a broken solarized. We should confirm that it's actually been taken out.

**Comment by Serubin** [comment]
https://github.com/Serubin/dotfiles/blob/develop/packages/cli/nvim/nvim.sh#L57

**Comment by Serubin** [comment]
Remoted.
